CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS item_requests (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    requester_id INT REFERENCES users(user_id),
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items (
    item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(500) NOT NULL,
    available Boolean NOT NULL,
    owner_id INT REFERENCES users(user_id),
    request_id INT REFERENCES item_requests(id)
);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start TIMESTAMP NOT NULL,
    ends TIMESTAMP NOT NULL,
    item_id INT REFERENCES items(item_id),
    booker_id INT REFERENCES users(user_id),
    booking_status varchar(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
    comment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(2000) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    item_id INT REFERENCES items(item_id),
    author_id INT REFERENCES users(user_id)
);